### ISSUE TITLE
ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by hellopython123** [xw-hu/Mask-ShadowGAN#10]
I run train_Mask-ShadowGAN.py and have  errors as following:
Traceback (most recent call last):
  File "train_Mask-ShadowGAN.py", line 140, in <module>
    batch_size=opt.batchSize, shuffle=True, num_workers=opt.n_cpu)
  File "F:\python3.5\lib\site-packages\torch\utils\data\dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "F:\python3.5\lib\site-packages\torch\utils\data\sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0
I don't know where to modify the dataset path or why len(self.data_ info)= =0.Can you give me some advice?
Thanks.

**Comment by RewindL** [comment]
Change "from datasets_USR import ImageDataset" to "from datasets_ISTD import ImageDataset" in "train_Mask-ShadowGAN" and have a try again.

**Comment by Arican-Lee** [comment]
Hello,I encountered the same problem, and I also tried to use the above method(Change "from datasets_USR import ImageDataset" to "from datasets_ISTD import ImageDataset" in "train_Mask-ShadowGAN" and have a try again.). But it won't work.Is there any other way?

**Comment by RewindL** [comment]
> Maybe you should check "dataroot" option in train_Mask-ShadowGAN is correct like "xxx/ISTD/", and also change path of "self.files_B" in ImageDataset from "train_C" to "train_C_fixed" or something else if you use adjusted ISTD dataset and shadow-free path is not end with "train_C". Good luck.



> Hello,I encountered the same problem, and I also tried to use the above method(Change "from datasets_USR import ImageDataset" to "from datasets_ISTD import ImageDataset" in "train_Mask-ShadowGAN" and have a try again.). But it won't work.Is there any other way?

**Comment by Arican-Lee** [comment]
Thank you for your reply.Do you want to make changes like this?
![1647777203(1)](https://user-images.githubusercontent.com/98862990/159160948-a5f99c37-37b0-4dc0-9699-ea40c5d84bdf.jpg)
However,the results did not change.
![1647777313(1)](https://user-images.githubusercontent.com/98862990/159160992-788c5cb0-7ef2-4f06-b32e-9e51cd8dee4d.jpg)

**Comment by RewindL** [comment]
> Thank you for your reply.Do you want to make changes like this? ![1647777203(1)](https://user-images.githubusercontent.com/98862990/159160948-a5f99c37-37b0-4dc0-9699-ea40c5d84bdf.jpg) However,the results did not change. ![1647777313(1)](https://user-images.githubusercontent.com/98862990/159160992-788c5cb0-7ef2-4f06-b32e-9e51cd8dee4d.jpg)

The dataroot option should be your own ISTD dataset's path, abviouly it should not be '/home/xwhu/dataset/train', make sure its correct. And also check "self.files_B" in ImageDataset, if you use adjusted ISTD dataset (ISTD+), shadow-free path might be "./train_C_fixed" or "./train_C_official_adjusted", make sure it's correct before you start training, or program can't find traning data with wrong training path.

**Comment by Mautong** [comment]
![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png)
Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?

**Comment by Mautong** [comment]
Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths？Thank you

**Comment by RewindL** [comment]
> ![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png) Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?Thank you

Try setting **opt.dataroot=r"D:\project\shadow-removal\Dataset\ISTD\"** (removing "train\train_C" in the end, and use prefix 'r' if you use \ in the path). 

Again, if your ISTD dataset contains "train/train_A", "train/train_B" and "train/train_C" by default, DO NOT CHANGE "self.files_B" in ImageDataset as metioned above. Just change opt.dataroot is enough.

**Comment by Arican-Lee** [comment]
![image](https://user-images.githubusercontent.com/98862990/159164790-c3c757af-ce92-4b64-bf59-c06d0f0a042a.png)
I have changed the path, but it showed this information, I don't understand what it means, maybe I can never run this code 

> > ![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png) Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?Thank you
> 
> Try setting **opt.dataroot=r"D:\project\shadow-removal\Dataset\ISTD"** (removing "train\train_C" in the end, and use prefix 'r' if you use \ in the path).
> 
> Again, if your ISTD dataset contains "train/train_A", "train/train_B" and "train/train_C" by default, DO NOT CHANGE "self.files_B" in ImageDataset as metioned above. Just change opt.dataroot is enough.

**Comment by RewindL** [comment]
> ![image](https://user-images.githubusercontent.com/98862990/159164790-c3c757af-ce92-4b64-bf59-c06d0f0a042a.png) I have changed the path, but it showed this information, I don't understand what it means, maybe I can never run this code
> 
> > > ![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png) Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?Thank you
> > 
> > 
> > Try setting **opt.dataroot=r"D:\project\shadow-removal\Dataset\ISTD"** (removing "train\train_C" in the end, and use prefix 'r' if you use \ in the path).
> > Again, if your ISTD dataset contains "train/train_A", "train/train_B" and "train/train_C" by default, DO NOT CHANGE "self.files_B" in ImageDataset as metioned above. Just change opt.dataroot is enough.

I don't understand why you set opt.dataroot="A:/project/shadow-remove/Mask-ShadowGAN-master/home/xwhu/dataset"? You have put ISTD dataset in this path? Why it's not end with "ISTD"?

**Comment by Mautong** [comment]
![image](https://user-images.githubusercontent.com/92156816/159165855-6e3c41d5-b6c7-4165-895c-04373b387783.png)
me too，but mine is end with "ISTD"


> > ![image](https://user-images.githubusercontent.com/98862990/159164790-c3c757af-ce92-4b64-bf59-c06d0f0a042a.png) I have changed the path, but it showed this information, I don't understand what it means, maybe I can never run this code
> > > > ![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png) Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?Thank you
> > > 
> > > 
> > > Try setting **opt.dataroot=r"D:\project\shadow-removal\Dataset\ISTD"** (removing "train\train_C" in the end, and use prefix 'r' if you use \ in the path).
> > > Again, if your ISTD dataset contains "train/train_A", "train/train_B" and "train/train_C" by default, DO NOT CHANGE "self.files_B" in ImageDataset as metioned above. Just change opt.dataroot is enough.
> 
> I don't understand why you set opt.dataroot="A:/project/shadow-remove/Mask-ShadowGAN-master/home/xwhu/dataset"? You have put ISTD dataset in this path? Why it's not end with "ISTD"?

**Comment by RewindL** [comment]
> ![image](https://user-images.githubusercontent.com/92156816/159165855-6e3c41d5-b6c7-4165-895c-04373b387783.png) me too，but mine is end with "ISTD"
> 
> > > ![image](https://user-images.githubusercontent.com/98862990/159164790-c3c757af-ce92-4b64-bf59-c06d0f0a042a.png) I have changed the path, but it showed this information, I don't understand what it means, maybe I can never run this code
> > > > > ![image](https://user-images.githubusercontent.com/92156816/159162327-5e269e04-7c2e-4335-bdee-e49713e4a1a6.png) Hello,I'm the partner of Lee, I'm wondering why this situation still happens. I have changed my data path., which is a path without shadow image. Should I add more paths?Thank you
> > > > 
> > > > 
> > > > Try setting **opt.dataroot=r"D:\project\shadow-removal\Dataset\ISTD"** (removing "train\train_C" in the end, and use prefix 'r' if you use \ in the path).
> > > > Again, if your ISTD dataset contains "train/train_A", "train/train_B" and "train/train_C" by default, DO NOT CHANGE "self.files_B" in ImageDataset as metioned above. Just change opt.dataroot is enough.
> > 
> > 
> > I don't understand why you set opt.dataroot="A:/project/shadow-remove/Mask-ShadowGAN-master/home/xwhu/dataset"? You have put ISTD dataset in this path? Why it's not end with "ISTD"?


Change opt.log_path = os.path.join('output', str(datetime.datetime.now()) + '.txt') to **opt.log_path = os.path.join('output/', str(datetime.datetime.now()) + '.txt')**

**Comment by Mautong** [comment]
still
![image](https://user-images.githubusercontent.com/92156816/159166366-af3eb3d4-b97b-40b0-9731-be35f3e26331.png)

**Comment by Arican-Lee** [comment]
> The authors only published the USR dataset. But previously obtained ISTD dataset from other place.

> If I end with "ISTD",the “ValueError: num_samples should be a positive integer value, but got num_samples=0” happen once again, so I end with "Train"，the suitation is the same.
![1647785248(1)](https://user-images.githubusercontent.com/98862990/159166425-4e77bbc1-e1b4-4ef7-9cc9-fd604f352955.png)

> If I don't end with thing,when I ran the code ,it happened “OSError: [Errno 22] Invalid argument: 'output\\2022-03-20 22:04:21.766201.txt'”
![1647785152(1)](https://user-images.githubusercontent.com/98862990/159166348-b224609b-8abf-415a-aa43-765b0bc8b8d0.png)

**Comment by RewindL** [comment]
> > The authors only published the USR dataset. But previously obtained ISTD dataset from other place.
> 
> > If I end with "ISTD",the “ValueError: num_samples should be a positive integer value, but got num_samples=0” happen once again, so I end with "Train"，the suitation is the same.
> > ![1647785248(1)](https://user-images.githubusercontent.com/98862990/159166425-4e77bbc1-e1b4-4ef7-9cc9-fd604f352955.png)
> 
> > If I don't end with thing,when I ran the code ,it happened “OSError: [Errno 22] Invalid argument: 'output\2022-03-20 22:04:21.766201.txt'”
> > ![1647785152(1)](https://user-images.githubusercontent.com/98862990/159166348-b224609b-8abf-415a-aa43-765b0bc8b8d0.png)

First, the dataroot means your ISTD dataset's path, it should have two subfolders "train" and "test", and program will find training image according ImageDataset. If you met num_samples=0, that means there is no images in corresponding path, so you should check your setting of dataroot and ImageDataset.

Second, there might be some problem if you run the code directly in Windows environment, i have not tried run it in Windows, so I am not sure whether the path is valid (for example, opt.log_path = os.path.join('output', str(datetime.datetime.now()) + '.txt')), I strongly recommend running the project in Linux, so that you can just download dataset and change dataroot path and successfully run training program. For Windows, I'm not very skilled, but according to the error prompt, it's caused by wrong path format.

**Comment by Mautong** [comment]
ohh,I see, I will try to use it in Linux, thank you for your precious time to help us

**Comment by Mautong** [comment]
> > > 作者只发布了 USR 数据集。但之前从其他地方获得了 ISTD 数据集。
> > 
> > 
> > > 如果我以“ISTD”结尾，“ValueError: num_samples should be an positive integer value, but got num_samples=0”又出现了一次，所以我以“Train”结尾，同样适用。
> > > ![1647785248(1)](https://user-images.githubusercontent.com/98862990/159166425-4e77bbc1-e1b4-4ef7-9cc9-fd604f352955.png)
> > 
> > 
> > > 如果我没有以事情结束，当我运行代码时，它发生了“OSError：[Errno 22] Invalid argument: 'output\2022-03-20 22:04:21.766201.txt'”
> > > ![1647785152(1)](https://user-images.githubusercontent.com/98862990/159166348-b224609b-8abf-415a-aa43-765b0bc8b8d0.png)
> 
> 首先，dataroot表示你的ISTD数据集的路径，它应该有两个子文件夹“train”和“test”，程序会根据ImageDataset找到训练图像。如果遇到num_samples=0，说明对应路径中没有图片，请检查dataroot和ImageDataset的设置。
> 
> 其次，直接在windows环境下运行代码可能会出问题，我没试过在windows下运行，所以不确定路径是否有效（比如opt.log_path = os.path.join( 'output', str(datetime.datetime.now()) + '.txt'))，我强烈建议在Linux下运行项目，这样你就可以下载数据集并更改dataroot路径并成功运行训练程序。对于windows，我不是很熟练，但是根据错误提示，是路径格式错误造成的。

哦，我明白了，我会尝试在Linux中使用它，感谢您宝贵的时间来帮助我们

**Comment by Mautong** [comment]
> > > The authors only published the USR dataset. But previously obtained ISTD dataset from other place.
> > 
> > 
> > > If I end with "ISTD",the “ValueError: num_samples should be a positive integer value, but got num_samples=0” happen once again, so I end with "Train"，the suitation is the same.
> > > ![1647785248(1)](https://user-images.githubusercontent.com/98862990/159166425-4e77bbc1-e1b4-4ef7-9cc9-fd604f352955.png)
> > 
> > 
> > > If I don't end with thing,when I ran the code ,it happened “OSError: [Errno 22] Invalid argument: 'output\2022-03-20 22:04:21.766201.txt'”
> > > ![1647785152(1)](https://user-images.githubusercontent.com/98862990/159166348-b224609b-8abf-415a-aa43-765b0bc8b8d0.png)
> 
> First, the dataroot means your ISTD dataset's path, it should have two subfolders "train" and "test", and program will find training image according ImageDataset. If you met num_samples=0, that means there is no images in corresponding path, so you should check your setting of dataroot and ImageDataset.
> 
> Second, there might be some problem if you run the code directly in Windows environment, i have not tried run it in Windows, so I am not sure whether the path is valid (for example, opt.log_path = os.path.join('output', str(datetime.datetime.now()) + '.txt')), I strongly recommend running the project in Linux, so that you can just download dataset and change dataroot path and successfully run training program. For Windows, I'm not very skilled, but according to the error prompt, it's caused by wrong path format.

ohh,I see, I will try to use it in Linux, thank you for your precious time to help us

**Comment by Arican-Lee** [comment]
Oh,Oh.Thank for your guidance. I don't have a Linux system, so I don't know. I'll get a Linux system first and then run it.
